DROP TABLE IF EXISTS products CASCADE;

-- PRODUCTS
CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price INTEGER NOT NULL,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  room_id INTEGER REFERENCES rooms(id) ON DELETE CASCADE,
  image VARCHAR(255) NOT NULL,
  provider INTEGER REFERENCES providers(id) ON DELETE CASCADE
);